### ISSUE TITLE
在编辑器中的详细配置

### ISSUE THREAD

**Issue by mickeyouyou** [xudianyang/yaf.auto.complete#1]
Setup in IDE PHPStorm
Menu "File" -> "Settings" -> "PHP" -> Select path to folder "yaf.auto.complete"

Setup in IDE NetBeans

Right click your project -> "Properties"
Select the "PHP Include Path" category
Click "Add Folder..."
Select your checkout of "php.auto.complete"
Click "Open"
Click "OK"

**Comment by MattCraftsCode** [comment]
Setup in IDE PHPStorm for mac
Menu "Settings" -> "Languages & Frameworks" -> "PHP" -> -> "Include Path" ->  + -> Select path to folder "yaf.auto.complete"
